mysql:
  image: quay.io/sameersbn/mysql:latest
  environment:
    - DB_USER=invoiceplane
    - DB_PASS=password
    - DB_NAME=invoiceplane_db
  volumes:
    - /srv/docker/invoiceplane/mysql:/var/lib/mysql

invoicePlane:
  image: quay.io/sameersbn/invoiceplane:1.4.3-2
  environment:
    - INVOICE_PLANE_FQDN=invoice.example.com
    - INVOICE_PLANE_TIMEZONE=Asia/Kolkata
  links:
    - mysql:mysql
  volumes:
    - /srv/docker/invoiceplane/invoiceplane:/var/lib/invoiceplane
    - /srv/docker/invoiceplane/nginx/sites-enabled:/etc/nginx/sites-enabled

nginx:
  image: quay.io/sameersbn/nginx:1.8.0-8
  links:
    - invoicePlane:invoiceplane-php-fpm
  volumes_from:
    - invoicePlane
  ports:
    - "10080:80"
