nginxSites:
  image: busybox
  volumes:
    - /srv/docker/invoiceplane/nginx/sites-enabled:/etc/nginx/sites-enabled
  command: tail -f /dev/null

mysql:
  image: sameersbn/mysql:latest
  environment:
    - DB_USER=invoice_plane
    - DB_PASS=password
    - DB_NAME=invoice_plane_db
  volumes:
    - /srv/docker/invoiceplane/mysql:/var/lib/mysql

invoicePlane:
  image: sameersbn/invoiceplane:latest
  environment:
    - INVOICE_PLANE_FQDN=invoice.example.com
    - INVOICE_PLANE_TIMEZONE=Asia/Kolkata
  links:
    - mysql:mysql
  volumes:
    - /srv/docker/invoiceplane/invoiceplane:/var/lib/invoiceplane
  volumes_from:
    - nginxSites

nginx:
  image: sameersbn/nginx
  links:
    - invoicePlane:php-fpm
  volumes_from:
    - nginxSites
    - invoicePlane
  ports:
    - "80:80"
