mysql:
  restart: always
  image: sameersbn/mysql:latest
  environment:
    - DB_USER=invoiceplane
    - DB_PASS=password
    - DB_NAME=invoiceplane_db
  volumes:
    - /srv/docker/invoiceplane/mysql:/var/lib/mysql

invoicePlane:
  restart: always
  image: sameersbn/invoiceplane:1.4.4
  command: app:invoiceplane
  environment:
    - DEBUG=false
    - TZ=Asia/Kolkata

    - INVOICEPLANE_TIMEZONE=Asia/Kolkata
    - INVOICEPLANE_FQDN=invoice.example.com

    - INVOICEPLANE_PHP_FPM_HOST=
    - INVOICEPLANE_PHP_FPM_PORT=

    - INVOICEPLANE_BACKUPS_EXPIRY=0
  links:
    - mysql:mysql
  volumes:
    - /srv/docker/invoiceplane/invoiceplane:/var/lib/invoiceplane

nginx:
  restart: always
  image: sameersbn/invoiceplane:1.4.4
  command: app:nginx
  links:
    - invoicePlane:php-fpm
  ports:
    - "10080:80"
